<head>
<link rel="stylesheet" href="css/pagina/ceusdospampas.css">
</head>


<section class="hero-wrap js-fullheight" id="sectionCeuSul" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight mainTitle">
            <div class="col-md-12 ftco-animate pb-5 mb-3">
                <h1 class="mb-3 bread tituloPrincipal">Céus <br />dos pampas</h1>
                <p class="mainSubTitle">
                    <span class="mr-2">
                        Conheça as constalações de povos antigos que habitaram
                        <br />a região dos pampas que olhavam para o céu de maneira diferente!
                    </span>
                </p>
            </div>
        </div>
    </div>
</section>

<div class="divisoria">
    <a href="javascript:;">
        <i class="fi fi-rr-angle-circle-down" aria-hidden="true"></i>
    </a>
</div>

<section class="sectionPageDefault" id="sectionCeuPampas">
    <div class="container containerPage">
        <div class="row">
            <div class="col-md-9">
                <p>A Astronomia é uma das ciências mais antigas do mundo, tendo registros de observações que datam
                    do período pré-histórico. Essas observações do céu noturno desempenharam um importante papel no
                    desenvolvimento da humanidade, pois permitiram aos povos antigos a distinção de tempo e épocas
                    de plantio através da elaboração de complexos calendários, como foi o caso dos povos que
                    habitaram a região da antiga Mesopotâmia. Pode-se dizer, portanto, que a construção desses
                    conhecimentos celestes contribuiu na sedentarização da Humanidade e no desenvolvimento das
                    primeiras civilizações.</p>
                <br />
                <p>No Brasil, nas Américas, povos originários também traçaram seus caminhos produzindo conhecimentos
                    e saberes que levaram ao desenvolvimento de suas sociedades. Processo abruptamente interrompido
                    com a chegada dos colonizadores. Conhecer, respeitar e divulgar este conhecimento é de extrema
                    importância para recuperarmos também a história do Brasil.</p>
            </div>
            <div class="col-md-3 imagem_destaque">
                <img src="./imagens_page/paginas/ceu_dos_pampas/camada2_imagemladotextodireitodoleitor_povokaigang_.png"
                    class="img-fluid">
                <p>Fonte: Wikimedia</p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 rodape">
                <p>
                    Confira abaixo algumas constelações que fazem parte deste cenário
                </p>

                <img src="./imagens_page/logos/logo planetarios do sul claro pronto.png" id="logoRodape">
            </div>
        </div>

    </div>
</section>

<div class="divisoria">
    <a href="#sectionObservador">
        <i class="fi fi-rr-angle-circle-down" aria-hidden="true"></i>
    </a>
</div>

<!-- <section class="sectionPageDefault" id="sectionObservador">
    <img src="./imagens_page/paginas/ceu_dos_pampas/camada3.1.png" id="imagem_sectionObservador_localizacao"
        usemap="#imagem-sectionObservador">

    <map name="imagem-sectionObservador">
        <area target="_self" alt="link1" title="link1" conteudo="0" class='open-popup' href="javascript:;"
            coords="607,782,41" shape="circle">
        <area target="_self" alt="link2" title="link2" conteudo="1" class='open-popup' href="javascript:;"
            coords="1046,936,39" shape="circle">
        <area target="_self" alt="link3" title="link3" conteudo="2" class='open-popup' href="javascript:;"
            coords="1144,904,39" shape="circle">
        <area target="_self" alt="link4" title="link4" conteudo="3" class='open-popup' href="javascript:;"
            coords="488,1487,40" shape="circle">
        <area target="_self" alt="link5" title="link5" conteudo="4" class='open-popup' href="javascript:;"
            coords="1112,1533,38" shape="circle">
    </map>
</section> -->

<section class="sectionPageDefault" id="sectionObservador">
    <!-- Image Map Generated by http://www.image-map.net/ -->
    <img src="./imagens_page/paginas/ceu_dos_pampas/camada3.1.png" id="imagem_sectionObservador_localizacao" usemap="#imagem-sectionObservador">

    <map name="imagem-sectionObservador">
        <area target="_self" alt="link1" title="link1" conteudo="0" class='open-popup' href="javascript:;" coords="607,782,41" shape="circle">
            <i class="fa fa-eye"></i>
        </area>
        <area target="_self" alt="link2" title="link2" conteudo="1" class='open-popup' href="javascript:;" coords="1046,936,39" shape="circle">
            <i class="fa fa-eye"></i>
        </area>
        <area target="_self" alt="link3" title="link3" conteudo="2" class='open-popup' href="javascript:;" coords="1144,904,39" shape="circle">
            <i class="fa fa-eye"></i>
        </area>
        <area target="_self" alt="link4" title="link4" conteudo="3" class='open-popup' href="javascript:;" coords="488,1487,40" shape="circle">
            <i class="fa fa-eye"></i>
        </area>
        <area target="_self" alt="link5" title="link5" conteudo="4" class='open-popup' href="javascript:;" coords="1112,1533,38" shape="circle">
            <i class="fa fa-eye"></i>
        </area>
    </map>
</section>

<section class="sectionPageDefault" id="sectionObservador2">
    <!-- Image Map Generated by http://www.image-map.net/ -->
    <img src="./imagens_page/paginas/ceu_dos_pampas/camada4.jpg" id="imagem_sectionObservador_localizacao2"
        usemap="#imagem-sectionObservador2">

        <map name="imagem-sectionObservador2">
            <area target="_self" alt="titulo1" conteudo="0" class='open-popup2' href="javascript:;" title="titulo1" coords="776,290,39" shape="circle">
            <area target="_self" alt="titulo2" conteudo="1" class='open-popup2' href="javascript:;" title="titulo2" coords="947,1068,38" shape="circle">
        </map>
</section>

<section class="sectionPageDefault" id="sectionConteudosDestaque">
    <div class="container containerPage">
        <hr>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div>
                        <img src="./imagens_page/calendario_cosmico/ABA1_posicao1_qtsceustemoceu.png" alt=""
                            class="img-fluid">
                    </div>
                    <div class="card-titulo">
                        <div class="titulo_principal">
                            Quantos <br />Céus tem <br />o Céu?
                        </div>

                        <div class="leiaMais">
                            <a href="index.php?page=quantos-ceus-tem-o-ceu">Leia mais ></a>
                        </div>
                    </div>
                    <div class="card-conteudo">
                        Desde tempos remotos, os astros foram observados, como inferimos dos registros arqueológicos e históricos, com diversos objetivos e propósitos. 
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div>
                        <img src="./imagens_page/calendario_cosmico/ABA1_posição2_oscéusdosul.png" alt=""
                            class="img-fluid">
                    </div>
                    <div class="card-titulo">
                        <div class="titulo_principal">
                            Os <br />Céus <br /> do Sul
                        </div>

                        <div class="leiaMais">
                            <a href="index.php?page=ceu-do-sul-detalhe">Leia mais ></a>
                        </div>
                    </div>
                    <div class="card-conteudo">
                        Os céus do Sul passaram a existir a partir da chegada dos primeiros habitantes humanos nestas terras. O “primeiro céu” sobre o Pampa foi observado e registrado pelos primeiros grupos de caçadores-coletores que chegaram aqui
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div>
                        <img src="./imagens_page/calendario_cosmico/Kaigang.png" alt=""
                            class="img-fluid">
                    </div>
                    <div class="card-titulo">
                        <div class="titulo_principal">
                            Os <br /> povos <br /> indígenas
                        </div>

                        <div class="leiaMais">
                            <a href="index.php?page=os-povos-indigenas-brasileiros">Leia mais ></a>
                        </div>
                    </div>
                    <div class="card-conteudo">
                        Os indígenas brasileiros perceberam que as atividades de pesca, caça, coleta e lavoura obedecem a flutuações sazonais. Assim, procuraram entender essas flutuações cíclicas a favor de sua subsistência, desenvolvendo seus saberes celestes.
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="sectionPageDefault" id="sectionSaibaMais">
    <div class="container containerPage">
        <hr>
        <p class="tituloSaibaMais"><img src="./imagens_page/paginas/ceu_dos_pampas/meteoro.png" alt="">Saiba Mais:</p>

        <div class="row conteudoLinksSaibaMais"></div>
    </div>
</section>


<section class="sectionPageDefault" id="sectionRodape">
    <div class="container containerPageRodape">
        <div>
            <a href="./index.php">
                <img src="./imagens_page/calendario_cosmico/voltar-ao-menuprincipal_png.png" class="logo" alt="">
            </a>
        </div>

        <div>
            <img src="./imagens_page/calendario_cosmico/explorarmais_png.png" class="logo" alt="">
        </div>
    </div>
</section>

<script src="js/pagina/ceusdospampas.js"></script>